### ISSUE TITLE
Add optional socials

### ISSUE THREAD

**Issue by filiptronicek** [taskord/taskord#189]
**Describe the bug**
It should be optional to fill out more than one social profile

**To Reproduce**

1. Go to your Profile settings
2. Fill out just some socials (e.g. just Twitter)
3. Save

**Expected behavior**

It should just accept whatever it gets.

**Screenshots**
![image](https://user-images.githubusercontent.com/29888641/89165116-637ab780-d578-11ea-98a5-463024e2e3ff.png)

**Comment by filiptronicek** [comment]
WDYT @dabbit

**Comment by dabbit** [comment]
Thanks @filiptronicek ❤️, It will be a quick patch!

**Comment by dabbit** [comment]
Fixed 🎉! Can you check now @filiptronicek?

If this issue persist feel free to reopen this issue!
