### ISSUE TITLE
Open Location in map provider

### ISSUE THREAD

**Issue by filiptronicek** [taskord/taskord#190]
**Describe the solution you'd like**

It would be nice to be able to click on the location on someone's profile and then open it with a map provider (e.g. OpenStreet Map, Google Maps, Apple Maps)

Example for Prague (Location string, which is on my profile)
https://www.openstreetmap.org/search?query=Prague%2C%20Czech%20republic

**Additional context**

The user could also set his preference of the map provider, similar to DuckDuckGo

**Comment by dabbit** [comment]
It will be a good addition!

**Comment by dabbit** [comment]
I think adding a field in DB for preference will reduce the performance. I think for now let it be pointed to Google Map.

PS: Twitter displays the location just as text!

**Comment by filiptronicek** [comment]
Yes, I know a lot of sites do that, including GitHub, but sometimes you just want to find that place :), I agree with just pointing to Google Maps
