### ISSUE TITLE
Cannot view user page

### ISSUE THREAD

**Issue by filiptronicek** [taskord/taskord#74]
To reproduce:
1. log out
1. go to a [user page](http://taskord-stg.herokuapp.com/@test)
1. See error:
![image](https://user-images.githubusercontent.com/29888641/88475076-f38f8000-cf2c-11ea-8c9e-05e7ed64f88f.png)

**Comment by evildabbit** [comment]
Thanks @filiptronicek, It is fixed now! Deployment is on the way https://stg.taskord.com/@test
